In [1]:
!pip install mobilechelonian


In [2]:
from mobilechelonian import Turtle

In [5]:
t=Turtle()
t.speed(5)
colours=["red","blue","yellow","brown","black","purple","green"]
t.penup(); t.left(90); t.forward(200); t.right(90); t.pendown()
for i in range (0,18):
    t.pencolor(colours[i%7])
    t.right(20)
    t.forward(50)
t.right(180)
t.home()

Turtle()

In [27]:
t=Turtle()
t.speed(5)
colours=["red","blue","yellow","brown","black","purple","green"]
t.penup(); t.left(180);# t.forward(200); t.right(90); t.pendown(); t.forward(180);

t.home()

Turtle()

In [4]:
vector_1=[1,2,3,4,5]
vector_2=[6,7,8,9,10]
vector_3=[]
x=0

while x<5:
    vector_3.append(vector_1[x]+vector_2[x])
    x=x+1
    
print(vector_3)
    

[7, 9, 11, 13, 15]


In [13]:
import numpy as np

In [12]:
vector_1=[1,2,3,4,5]
vector_2=[6,7,8,9,10]
vector_3=[]
x=0

while x<len(vector_1):
    vector_3.append(vector_1[x]-vector_2[x])
    x=x+1
    
print(vector_3)

[-5, -5, -5, -5, -5]


In [14]:
vector_1=[2,1,3]
vector_2=[4,6,7]
x=0
producto_punto=0

while x<len(vector_1):
    producto_punto=producto_punto+vector_1[x]*vector_2[x]
    x=x+1
    
print(producto_punto)

35


In [16]:
A=np.array([[1,3,2],[1,0,0],[1,2,2]])
B=np.array([[1,0,5],
            [7,5,0],
            [2,1,1]])
print (A)
print('\n')
print (B)

[[1 3 2]
 [1 0 0]
 [1 2 2]]


[[1 0 5]
 [7 5 0]
 [2 1 1]]


In [17]:
A+B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [18]:
A-B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [21]:
A*2

array([[2, 6, 4],
       [2, 0, 0],
       [2, 4, 4]])

In [22]:
A*B

array([[ 1,  0, 10],
       [ 7,  0,  0],
       [ 2,  2,  2]])

In [23]:
B@A

array([[ 6, 13, 12],
       [12, 21, 14],
       [ 4,  8,  6]])

In [24]:
B*3

array([[ 3,  0, 15],
       [21, 15,  0],
       [ 6,  3,  3]])

In [25]:
A.shape

(3, 3)

In [30]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [41]:
np.linalg.det(A)

-2.0

In [49]:
A=np.array([[1,-2],
            [3,2],])

B=np.array([[1],
            [11],])

np.linalg.inv(A)@B

array([[3.],
       [1.]])

In [51]:
A=np.array([[1,2,3],
            [2,5,2],
            [6,-3,1]])

B=np.array([[6],
            [4],
            [2]])

np.linalg.inv(A)@B

array([[-1.11022302e-16],
       [-6.93889390e-17],
       [ 2.00000000e+00]])